// <auto-generated />
using System;
using IndependentApproval.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndependentApproval.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IndependentApprovalDbContext))]
    [Migration("20260824102937_AddRequestTypesAndRequestFoundation")]
    partial class AddRequestTypesAndRequestFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ArchivedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ArchivedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByAccount")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionArabic")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DescriptionEnglish")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("NormalizedCode")
                        .IsUnique();

                    b.HasIndex("IsArchived", "IsActive");

                    b.ToTable("ApplicationRoles", "app", t =>
                        {
                            t.HasCheckConstraint("CK_ApplicationRoles_ArchivedInactive", "[IsArchived] = 0 OR [IsActive] = 0");
                        });
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("AdObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("AdSid")
                        .IsRequired()
                        .HasColumnType("varbinary(68)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByAccount")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRemoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastSuccessfulAccessAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LockReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("LockedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LockedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedAccountName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("RemovedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RemovedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("RemovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserPrincipalName")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("AdObjectGuid")
                        .IsUnique()
                        .HasFilter("[AdObjectGuid] IS NOT NULL");

                    b.HasIndex("AdSid")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("NormalizedAccountName")
                        .IsUnique();

                    b.HasIndex("RemovedByUserId");

                    b.HasIndex("IsRemoved", "IsActive", "IsLocked");

                    b.ToTable("ApplicationUsers", "app");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("AssignedByAccount")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RemovedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RemovedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("RemovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("RemovedByUserId");

                    b.HasIndex("ApplicationRoleId", "RemovedAtUtc");

                    b.HasIndex("ApplicationUserId", "ApplicationRoleId")
                        .IsUnique();

                    b.ToTable("ApplicationUserRoles", "app");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriptionArabic")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionEnglish")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8fcb6c1-8b0a-4ee5-a0cf-726df70a1001"),
                            Code = "APPLICATION.ACCESS",
                            DescriptionArabic = "الوصول إلى التطبيق بعد مصادقة Windows.",
                            DescriptionEnglish = "Access the application after Windows authentication.",
                            NameArabic = "الوصول إلى التطبيق",
                            NameEnglish = "Access application"
                        },
                        new
                        {
                            Id = new Guid("a8fcb6c1-8b0a-4ee5-a0cf-726df70a1002"),
                            Code = "REQUESTS.START",
                            DescriptionArabic = "إنشاء الطلبات وإرسالها ضمن سير عمل مسموح.",
                            DescriptionEnglish = "Create and submit requests for an allowed workflow.",
                            NameArabic = "بدء الطلبات",
                            NameEnglish = "Start requests"
                        },
                        new
                        {
                            Id = new Guid("a8fcb6c1-8b0a-4ee5-a0cf-726df70a1003"),
                            Code = "TASKS.PROCESS_ASSIGNED",
                            DescriptionArabic = "معالجة مهام سير العمل المسندة إلى أدوار المستخدم.",
                            DescriptionEnglish = "Process workflow tasks assigned to the user's roles.",
                            NameArabic = "معالجة المهام المسندة",
                            NameEnglish = "Process assigned tasks"
                        },
                        new
                        {
                            Id = new Guid("a8fcb6c1-8b0a-4ee5-a0cf-726df70a1004"),
                            Code = "REQUESTS.VIEW_ALLOWED",
                            DescriptionArabic = "عرض الطلبات التي تسمح بها قواعد سير العمل والأدوار.",
                            DescriptionEnglish = "View requests allowed by workflow and role rules.",
                            NameArabic = "عرض الطلبات المسموح بها",
                            NameEnglish = "View allowed requests"
                        },
                        new
                        {
                            Id = new Guid("a8fcb6c1-8b0a-4ee5-a0cf-726df70a1005"),
                            Code = "DOCUMENTS.MANAGE",
                            DescriptionArabic = "رفع المستندات وفتحها وإدارتها عندما تسمح قواعد سير العمل بذلك.",
                            DescriptionEnglish = "Upload, open and manage documents when workflow rules allow it.",
                            NameArabic = "إدارة المستندات",
                            NameEnglish = "Manage documents"
                        },
                        new
                        {
                            Id = new Guid("a8fcb6c1-8b0a-4ee5-a0cf-726df70a1006"),
                            Code = "ADMINISTRATION.VIEW",
                            DescriptionArabic = "عرض معلومات الإدارة دون منح صلاحية مسؤول النظام.",
                            DescriptionEnglish = "View administration information without granting system administrator access.",
                            NameArabic = "عرض الإدارة",
                            NameEnglish = "View administration"
                        });
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("GrantedByAccount")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RemovedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RemovedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("RemovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("RemovedByUserId");

                    b.HasIndex("ApplicationRoleId", "PermissionId")
                        .IsUnique();

                    b.HasIndex("PermissionId", "RemovedAtUtc");

                    b.ToTable("RolePermissions", "app");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Documents.DocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("UploadedAtUtc");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Documents", "app");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("CurrentWorkflowStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestTypeVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "RequestTypeVersionId")
                        .HasName("AK_ApprovalRequests_Id_RequestTypeVersionId");

                    b.HasIndex("CurrentWorkflowStepId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("RequestTypeVersionId", "RequestTypeId");

                    b.HasIndex("RequestTypeVersionId", "Status");

                    b.HasIndex("WorkflowVersionId", "Status");

                    b.HasIndex("RequestedByUserId", "Status", "ModifiedAtUtc");

                    b.ToTable("ApprovalRequests", "app", t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalRequests_CompletedAtUtc_Chronology", "[CompletedAtUtc] IS NULL OR [CompletedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_ApprovalRequests_CurrentWorkflowStepId_NotEmpty", "[CurrentWorkflowStepId] IS NULL OR [CurrentWorkflowStepId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_ApprovalRequests_ModifiedAtUtc_Chronology", "[ModifiedAtUtc] IS NULL OR [ModifiedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_ApprovalRequests_Status_Valid", "[Status] IN ('Draft', 'Submitted', 'InProgress', 'OnHold', 'MoreInformationRequired', 'Approved', 'Rejected', 'Completed', 'Cancelled')");

                            t.HasCheckConstraint("CK_ApprovalRequests_SubmittedAtUtc_Chronology", "[SubmittedAtUtc] IS NULL OR [SubmittedAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_ApprovalRequests_WorkflowDefinitionId_NotEmpty", "[WorkflowDefinitionId] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_ApprovalRequests_WorkflowVersionId_NotEmpty", "[WorkflowVersionId] <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestContentValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ModifiedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestFieldDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestTypeVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("ModifiedByApplicationUserId");

                    b.HasIndex("RequestFieldDefinitionId");

                    b.HasIndex("ApprovalRequestId", "RequestFieldDefinitionId")
                        .IsUnique();

                    b.HasIndex("ApprovalRequestId", "RequestTypeVersionId");

                    b.HasIndex("RequestFieldDefinitionId", "RequestTypeVersionId");

                    b.ToTable("RequestContentValues", "app", t =>
                        {
                            t.HasCheckConstraint("CK_RequestContentValues_ValueJson_Valid", "ISJSON(CONCAT('[', [ValueJson], ']')) = 1");
                        });
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AttachedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("AttachedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestFieldDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestTypeVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttachedByApplicationUserId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ApprovalRequestId", "RequestTypeVersionId");

                    b.HasIndex("RequestFieldDefinitionId", "RequestTypeVersionId");

                    b.HasIndex("ApprovalRequestId", "RequestFieldDefinitionId", "DocumentId")
                        .IsUnique();

                    b.HasIndex("ApprovalRequestId", "RequestFieldDefinitionId", "SortOrder");

                    b.ToTable("RequestDocuments", "app", t =>
                        {
                            t.HasCheckConstraint("CK_RequestDocuments_SortOrder_NonNegative", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChoiceConfigurationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByAccount")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HelpTextArabic")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HelpTextEnglish")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LabelArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LabelEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RequestTypeVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ValidationConfigurationJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "RequestTypeVersionId")
                        .HasName("AK_RequestFieldDefinitions_Id_RequestTypeVersionId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("RequestTypeVersionId", "IsActive");

                    b.HasIndex("RequestTypeVersionId", "NormalizedKey")
                        .IsUnique();

                    b.HasIndex("RequestTypeVersionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RequestFieldDefinitions", "app", t =>
                        {
                            t.HasCheckConstraint("CK_RequestFieldDefinitions_ChoiceConfigurationJson_Valid", "[ChoiceConfigurationJson] IS NULL OR ISJSON([ChoiceConfigurationJson]) = 1");

                            t.HasCheckConstraint("CK_RequestFieldDefinitions_DefaultValueJson_Valid", "[DefaultValueJson] IS NULL OR ISJSON(CONCAT('[', [DefaultValueJson], ']')) = 1");

                            t.HasCheckConstraint("CK_RequestFieldDefinitions_DocumentMode_FieldType", "(([FieldType] IN ('FileDocument', 'RichDocument') AND [DocumentMode] IS NOT NULL) OR ([FieldType] NOT IN ('FileDocument', 'RichDocument') AND [DocumentMode] IS NULL))");

                            t.HasCheckConstraint("CK_RequestFieldDefinitions_DocumentMode_Valid", "[DocumentMode] IS NULL OR [DocumentMode] IN ('UploadOnly', 'CreateInEditorOnly', 'UploadOrCreate')");

                            t.HasCheckConstraint("CK_RequestFieldDefinitions_FieldType_Valid", "[FieldType] IN ('ShortText', 'LongText', 'Integer', 'Decimal', 'Date', 'DateTime', 'YesNo', 'SingleChoice', 'MultipleChoice', 'ActiveDirectoryUser', 'ApplicationRole', 'FileDocument', 'RichDocument')");

                            t.HasCheckConstraint("CK_RequestFieldDefinitions_SortOrder_NonNegative", "[SortOrder] >= 0");

                            t.HasCheckConstraint("CK_RequestFieldDefinitions_ValidationConfigurationJson_Valid", "[ValidationConfigurationJson] IS NULL OR ISJSON([ValidationConfigurationJson]) = 1");
                        });
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestNumberSequence", b =>
                {
                    b.Property<string>("NormalizedPrefix")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<long>("NextValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("NormalizedPrefix", "Year");

                    b.ToTable("RequestNumberSequences", "app", t =>
                        {
                            t.HasCheckConstraint("CK_RequestNumberSequences_NextValue_Positive", "[NextValue] > 0");

                            t.HasCheckConstraint("CK_RequestNumberSequences_NormalizedPrefix_Valid", "LEN([NormalizedPrefix]) > 0 AND [NormalizedPrefix] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^A-Z0-9-]%' COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_RequestNumberSequences_Year_Valid", "[Year] BETWEEN 1 AND 9999");
                        });
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestRichDocumentRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentLength")
                        .HasColumnType("int");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestFieldDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestTypeVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SanitizerVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("RequestFieldDefinitionId");

                    b.HasIndex("ApprovalRequestId", "RequestTypeVersionId");

                    b.HasIndex("RequestFieldDefinitionId", "RequestTypeVersionId");

                    b.HasIndex("ApprovalRequestId", "RequestFieldDefinitionId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("RequestRichDocumentRevisions", "app", t =>
                        {
                            t.HasCheckConstraint("CK_RequestRichDocumentRevisions_ContentLength_NonNegative", "[ContentLength] >= 0");

                            t.HasCheckConstraint("CK_RequestRichDocumentRevisions_ContentSha256_Valid", "LEN([ContentSha256]) = 64 AND [ContentSha256] NOT LIKE '%[^0-9A-Fa-f]%'");

                            t.HasCheckConstraint("CK_RequestRichDocumentRevisions_RevisionNumber_Positive", "[RevisionNumber] > 0");
                        });
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ArchivedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ArchivedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByAccount")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("NormalizedCode")
                        .IsUnique();

                    b.ToTable("RequestTypes", "app", t =>
                        {
                            t.HasCheckConstraint("CK_RequestTypes_Code_NotBlank", "LEN(LTRIM(RTRIM([Code]))) > 0");

                            t.HasCheckConstraint("CK_RequestTypes_NormalizedCode_NotBlank", "LEN(LTRIM(RTRIM([NormalizedCode]))) > 0");
                        });
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestTypeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ArchivedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ArchivedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByAccount")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionArabic")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DescriptionEnglish")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NavigationOrder")
                        .HasColumnType("int");

                    b.Property<string>("NavigationSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PublishedByAccount")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestPrefix")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "RequestTypeId")
                        .HasName("AK_RequestTypeVersions_Id_RequestTypeId");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("RequestTypeId")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestTypeVersions_RequestTypeId_Draft")
                        .HasFilter("[Lifecycle] = 'Draft'");

                    b.HasIndex("Lifecycle", "NavigationOrder");

                    b.HasIndex("Lifecycle", "NavigationSlug");

                    b.HasIndex("RequestTypeId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RequestTypeVersions", "app", t =>
                        {
                            t.HasCheckConstraint("CK_RequestTypeVersions_ArchivedAudit", "[Lifecycle] <> 'Archived' OR [ArchivedAtUtc] IS NOT NULL");

                            t.HasCheckConstraint("CK_RequestTypeVersions_Lifecycle_Valid", "[Lifecycle] IN ('Draft', 'Published', 'Archived')");

                            t.HasCheckConstraint("CK_RequestTypeVersions_NavigationOrder_NonNegative", "[NavigationOrder] >= 0");

                            t.HasCheckConstraint("CK_RequestTypeVersions_PublishedAudit", "[Lifecycle] <> 'Published' OR [PublishedAtUtc] IS NOT NULL");

                            t.HasCheckConstraint("CK_RequestTypeVersions_VersionNumber_Positive", "[VersionNumber] > 0");
                        });
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.ApplicationRole", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.ApplicationUser", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("LockedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RemovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.ApplicationUserRole", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationRole", "ApplicationRole")
                        .WithMany("UserAssignments")
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", "ApplicationUser")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RemovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationRole");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.RolePermission", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationRole", "ApplicationRole")
                        .WithMany("PermissionAssignments")
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.Permission", "Permission")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RemovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationRole");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.ApprovalRequest", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Requests.RequestType", "RequestType")
                        .WithMany("Requests")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Requests.RequestTypeVersion", "RequestTypeVersion")
                        .WithMany("Requests")
                        .HasForeignKey("RequestTypeVersionId", "RequestTypeId")
                        .HasPrincipalKey("Id", "RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestType");

                    b.Navigation("RequestTypeVersion");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestContentValue", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", "ModifiedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Requests.ApprovalRequest", "ApprovalRequest")
                        .WithMany("ContentValues")
                        .HasForeignKey("ApprovalRequestId", "RequestTypeVersionId")
                        .HasPrincipalKey("Id", "RequestTypeVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Requests.RequestFieldDefinition", "RequestFieldDefinition")
                        .WithMany("ContentValues")
                        .HasForeignKey("RequestFieldDefinitionId", "RequestTypeVersionId")
                        .HasPrincipalKey("Id", "RequestTypeVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("ModifiedByApplicationUser");

                    b.Navigation("RequestFieldDefinition");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestDocument", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", "AttachedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("AttachedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Documents.DocumentRecord", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Requests.ApprovalRequest", "ApprovalRequest")
                        .WithMany("Documents")
                        .HasForeignKey("ApprovalRequestId", "RequestTypeVersionId")
                        .HasPrincipalKey("Id", "RequestTypeVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Requests.RequestFieldDefinition", "RequestFieldDefinition")
                        .WithMany("Documents")
                        .HasForeignKey("RequestFieldDefinitionId", "RequestTypeVersionId")
                        .HasPrincipalKey("Id", "RequestTypeVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");

                    b.Navigation("AttachedByApplicationUser");

                    b.Navigation("Document");

                    b.Navigation("RequestFieldDefinition");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestFieldDefinition", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Requests.RequestTypeVersion", "RequestTypeVersion")
                        .WithMany("Fields")
                        .HasForeignKey("RequestTypeVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestTypeVersion");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestRichDocumentRevision", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", "CreatedByApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Requests.ApprovalRequest", "ApprovalRequest")
                        .WithMany("RichDocumentRevisions")
                        .HasForeignKey("ApprovalRequestId", "RequestTypeVersionId")
                        .HasPrincipalKey("Id", "RequestTypeVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndependentApproval.Api.Domain.Requests.RequestFieldDefinition", "RequestFieldDefinition")
                        .WithMany("RichDocumentRevisions")
                        .HasForeignKey("RequestFieldDefinitionId", "RequestTypeVersionId")
                        .HasPrincipalKey("Id", "RequestTypeVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");

                    b.Navigation("CreatedByApplicationUser");

                    b.Navigation("RequestFieldDefinition");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestType", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestTypeVersion", b =>
                {
                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Administration.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IndependentApproval.Api.Domain.Requests.RequestType", "RequestType")
                        .WithMany("Versions")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.ApplicationRole", b =>
                {
                    b.Navigation("PermissionAssignments");

                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.ApplicationUser", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Administration.Permission", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.ApprovalRequest", b =>
                {
                    b.Navigation("ContentValues");

                    b.Navigation("Documents");

                    b.Navigation("RichDocumentRevisions");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestFieldDefinition", b =>
                {
                    b.Navigation("ContentValues");

                    b.Navigation("Documents");

                    b.Navigation("RichDocumentRevisions");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestType", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("IndependentApproval.Api.Domain.Requests.RequestTypeVersion", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
